/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Evaluacion_empresas;

/**
 *
 * @author Jean Carlo
 */
public class vp extends javax.swing.JFrame {

    /**
     * Creates new form vp
     */
    public vp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelmain = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        diag = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Diagnostico = new javax.swing.JLabel();
        vpPanel1 = new javax.swing.JPanel();
        RazSoc = new javax.swing.JLabel();
        Preg1 = new javax.swing.JLabel();
        Preg2 = new javax.swing.JLabel();
        RazSocial = new javax.swing.JTextField();
        si1 = new javax.swing.JRadioButton();
        no1 = new javax.swing.JRadioButton();
        no2 = new javax.swing.JRadioButton();
        si2 = new javax.swing.JRadioButton();
        si3 = new javax.swing.JRadioButton();
        no3 = new javax.swing.JRadioButton();
        si4 = new javax.swing.JRadioButton();
        no4 = new javax.swing.JRadioButton();
        Preg3 = new javax.swing.JLabel();
        Preg4 = new javax.swing.JLabel();
        Factores1 = new javax.swing.JLabel();
        Preg6 = new javax.swing.JLabel();
        si5 = new javax.swing.JRadioButton();
        no5 = new javax.swing.JRadioButton();
        Preg16 = new javax.swing.JLabel();
        si6 = new javax.swing.JRadioButton();
        no6 = new javax.swing.JRadioButton();
        Preg7 = new javax.swing.JLabel();
        si7 = new javax.swing.JRadioButton();
        no7 = new javax.swing.JRadioButton();
        Factores2 = new javax.swing.JLabel();
        Preg8 = new javax.swing.JLabel();
        si8 = new javax.swing.JRadioButton();
        no8 = new javax.swing.JRadioButton();
        Preg9 = new javax.swing.JLabel();
        si9 = new javax.swing.JRadioButton();
        no9 = new javax.swing.JRadioButton();
        Preg10 = new javax.swing.JLabel();
        si10 = new javax.swing.JRadioButton();
        no10 = new javax.swing.JRadioButton();
        Preg11 = new javax.swing.JLabel();
        si11 = new javax.swing.JRadioButton();
        no11 = new javax.swing.JRadioButton();
        Preg12 = new javax.swing.JLabel();
        si12 = new javax.swing.JRadioButton();
        no12 = new javax.swing.JRadioButton();
        Preg13 = new javax.swing.JLabel();
        si13 = new javax.swing.JRadioButton();
        no13 = new javax.swing.JRadioButton();
        Preg14 = new javax.swing.JLabel();
        si14 = new javax.swing.JRadioButton();
        no14 = new javax.swing.JRadioButton();
        Preg15 = new javax.swing.JLabel();
        si15 = new javax.swing.JRadioButton();
        no15 = new javax.swing.JRadioButton();
        si16 = new javax.swing.JRadioButton();
        no16 = new javax.swing.JRadioButton();
        Factores3 = new javax.swing.JLabel();
        Factores4 = new javax.swing.JLabel();
        Preg5 = new javax.swing.JLabel();
        Preg17 = new javax.swing.JLabel();
        Preg18 = new javax.swing.JLabel();
        Preg19 = new javax.swing.JLabel();
        Preg20 = new javax.swing.JLabel();
        vpPanel2 = new javax.swing.JPanel();
        Panel1 = new javax.swing.JPanel();
        Panel2 = new javax.swing.JPanel();
        Panel3 = new javax.swing.JPanel();
        Panel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setBackground(java.awt.Color.blue);
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ENCUESTA");
        jLabel8.setAutoscrolls(true);

        jLabel9.setBackground(java.awt.Color.blue);
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("RESULTADOS");
        jLabel9.setAutoscrolls(true);

        jLabel7.setBackground(java.awt.Color.blue);
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DE NUEVOS NEGOCIOS EN LIMA METROPOLITANA");
        jLabel7.setAutoscrolls(true);

        jLabel6.setBackground(java.awt.Color.blue);
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("FACTORES DETERMINANTES DEL ÉXITO DEL EMPRENDIMIENTO ");
        jLabel6.setAutoscrolls(true);

        diag.setBackground(new java.awt.Color(255, 255, 255));
        diag.setAlignmentX(0.0F);
        diag.setAlignmentY(0.0F);
        diag.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Conclusión:");

        javax.swing.GroupLayout diagLayout = new javax.swing.GroupLayout(diag);
        diag.setLayout(diagLayout);
        diagLayout.setHorizontalGroup(
            diagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Diagnostico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        diagLayout.setVerticalGroup(
            diagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diagLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(diagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Diagnostico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        vpPanel1.setBackground(java.awt.Color.white);

        RazSoc.setText("Razon Social");

        Preg1.setText("1. Cuenta con fuentes de financiamiento");
        Preg1.setPreferredSize(new java.awt.Dimension(526, 14));

        Preg2.setText("2. Cuenta con una inversión efectuada en  Existencias (Mercaderías)");

        si1.setText("si");
        si1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                si1ActionPerformed(evt);
            }
        });

        no1.setBackground(java.awt.Color.white);
        no1.setText("no");
        no1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no1ActionPerformed(evt);
            }
        });

        no2.setBackground(java.awt.Color.white);
        no2.setText("no");
        no2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no2ActionPerformed(evt);
            }
        });

        si2.setText("si");
        si2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                si2ActionPerformed(evt);
            }
        });

        si3.setBackground(java.awt.Color.white);
        si3.setText("si");
        si3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                si3ActionPerformed(evt);
            }
        });

        no3.setBackground(java.awt.Color.white);
        no3.setText("no");
        no3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no3ActionPerformed(evt);
            }
        });

        si4.setBackground(java.awt.Color.white);
        si4.setText("si");
        si4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                si4ActionPerformed(evt);
            }
        });

        no4.setBackground(java.awt.Color.white);
        no4.setText("no");
        no4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no4ActionPerformed(evt);
            }
        });

        Preg3.setText("3. Cuenta con una inversión efectuada en Activos Fijos (Muebles e Inmuebles)");

        Preg4.setText("4. El negocio genera ingresos");

        Factores1.setBackground(java.awt.Color.blue);
        Factores1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Factores1.setForeground(new java.awt.Color(0, 0, 204));
        Factores1.setText("A) FACTORES ECONOMICOS DEL NEGOCIO");

        Preg6.setText("6. Sus costos y gastos en la gestion del negocio son siempre menores al valor de");

        si5.setBackground(java.awt.Color.white);
        si5.setText("si");
        si5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                si5ActionPerformed(evt);
            }
        });

        no5.setBackground(java.awt.Color.white);
        no5.setText("no");
        no5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no5ActionPerformed(evt);
            }
        });

        Preg16.setText("16. Cuenta con una página web o redes sociales para publicitar su necgocio");

        si6.setBackground(java.awt.Color.white);
        si6.setText("si");
        si6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                si6ActionPerformed(evt);
            }
        });

        no6.setBackground(java.awt.Color.white);
        no6.setText("no");
        no6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no6ActionPerformed(evt);
            }
        });

        Preg7.setText("7. Tiene Ruc");

        si7.setBackground(java.awt.Color.white);
        si7.setText("si");
        si7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                si7ActionPerformed(evt);
            }
        });

        no7.setBackground(java.awt.Color.white);
        no7.setText("no");
        no7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no7ActionPerformed(evt);
            }
        });

        Factores2.setBackground(java.awt.Color.blue);
        Factores2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Factores2.setForeground(new java.awt.Color(0, 0, 204));
        Factores2.setText("B) FACTORES REGULATORIOS DEL NEGOCIO");

        Preg8.setText("8. Conoce los regimenes Tributarios de la Sunat");

        si8.setBackground(java.awt.Color.white);
        si8.setText("si");
        si8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                si8ActionPerformed(evt);
            }
        });

        no8.setBackground(java.awt.Color.white);
        no8.setText("no");
        no8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no8ActionPerformed(evt);
            }
        });

        Preg9.setText("9. Cuenta con licencia de funcionamiento de la Municipalidad");

        si9.setBackground(java.awt.Color.white);
        si9.setText("si");
        si9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                si9ActionPerformed(evt);
            }
        });

        no9.setBackground(java.awt.Color.white);
        no9.setText("no");
        no9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no9ActionPerformed(evt);
            }
        });

        Preg10.setText("10. Conoce los requisitos exigidos por Defensa Civil");

        si10.setBackground(java.awt.Color.white);
        si10.setText("si");
        si10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                si10ActionPerformed(evt);
            }
        });

        no10.setText("no");
        no10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no10ActionPerformed(evt);
            }
        });

        Preg11.setText("11. Cumple con regularidad con los pagos de sus obligaciones tributarias");

        si11.setText("si");
        si11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                si11ActionPerformed(evt);
            }
        });

        no11.setBackground(java.awt.Color.white);
        no11.setText("no");
        no11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no11ActionPerformed(evt);
            }
        });

        Preg12.setText("12. Emite comprobante de pago (boletas de venta, tickets - facturas)");

        si12.setBackground(java.awt.Color.white);
        si12.setText("si");
        si12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                si12ActionPerformed(evt);
            }
        });

        no12.setText("no");
        no12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no12ActionPerformed(evt);
            }
        });

        Preg13.setText("13. Cumple periodicamente con los pagos y renovación de la licencia de");

        si13.setBackground(java.awt.Color.white);
        si13.setText("si");
        si13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                si13ActionPerformed(evt);
            }
        });

        no13.setText("no");
        no13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no13ActionPerformed(evt);
            }
        });

        Preg14.setText("14. Genera siempre propuesta de valor o innovación en la actividad que emprende");

        si14.setBackground(java.awt.Color.white);
        si14.setText("si");
        si14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                si14ActionPerformed(evt);
            }
        });

        no14.setBackground(java.awt.Color.white);
        no14.setText("no");
        no14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no14ActionPerformed(evt);
            }
        });

        Preg15.setText("15. Tiene la capacidad de manejar adecuadamente sus emociones e influir en las");

        si15.setBackground(java.awt.Color.white);
        si15.setText("si");
        si15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                si15ActionPerformed(evt);
            }
        });

        no15.setText("no");
        no15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no15ActionPerformed(evt);
            }
        });

        si16.setBackground(java.awt.Color.white);
        si16.setText("si");
        si16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                si16ActionPerformed(evt);
            }
        });

        no16.setBackground(java.awt.Color.white);
        no16.setText("no");
        no16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no16ActionPerformed(evt);
            }
        });

        Factores3.setBackground(java.awt.Color.blue);
        Factores3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Factores3.setForeground(new java.awt.Color(0, 0, 204));
        Factores3.setText("C) FACTORES PERSONALES");

        Factores4.setBackground(java.awt.Color.blue);
        Factores4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Factores4.setForeground(new java.awt.Color(0, 0, 204));
        Factores4.setText("(Evalua en que situación regulatoria en la que se encuentra el negocio)");

        Preg5.setText("5. Sus ingresos generan rentabilidad");

        Preg17.setText("venta de sus servicios o existencia.");

        Preg18.setText("o realiza, y asume nuevos retos.");

        Preg19.setText("funcionamiento de su negocion licencia de funcionamiento de la Municipalidad.");

        Preg20.setText("emociones de los demás cuando se interlaciona.");

        javax.swing.GroupLayout vpPanel1Layout = new javax.swing.GroupLayout(vpPanel1);
        vpPanel1.setLayout(vpPanel1Layout);
        vpPanel1Layout.setHorizontalGroup(
            vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vpPanel1Layout.createSequentialGroup()
                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vpPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Preg4, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Preg1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Preg5, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Preg2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Preg3, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Preg6)
                            .addGroup(vpPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(vpPanel1Layout.createSequentialGroup()
                                        .addComponent(si3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(no3))
                                    .addGroup(vpPanel1Layout.createSequentialGroup()
                                        .addComponent(si4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(no4))
                                    .addGroup(vpPanel1Layout.createSequentialGroup()
                                        .addComponent(si5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(no5))
                                    .addGroup(vpPanel1Layout.createSequentialGroup()
                                        .addComponent(si1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(no1))
                                    .addGroup(vpPanel1Layout.createSequentialGroup()
                                        .addComponent(si2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(no2))))
                            .addGroup(vpPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(vpPanel1Layout.createSequentialGroup()
                                        .addComponent(si6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(no6))
                                    .addComponent(Preg17, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(vpPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vpPanel1Layout.createSequentialGroup()
                                .addComponent(si15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(no15))
                            .addGroup(vpPanel1Layout.createSequentialGroup()
                                .addComponent(si14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(no14))))
                    .addGroup(vpPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vpPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Preg7, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Preg8, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Preg9, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Preg10, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Factores4, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Preg11, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Preg12)
                                    .addGroup(vpPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(vpPanel1Layout.createSequentialGroup()
                                                .addComponent(si7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(no7))
                                            .addGroup(vpPanel1Layout.createSequentialGroup()
                                                .addComponent(si8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(no8))
                                            .addGroup(vpPanel1Layout.createSequentialGroup()
                                                .addComponent(si9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(no9))
                                            .addGroup(vpPanel1Layout.createSequentialGroup()
                                                .addComponent(si10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(no10))
                                            .addGroup(vpPanel1Layout.createSequentialGroup()
                                                .addComponent(si11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(no11))
                                            .addGroup(vpPanel1Layout.createSequentialGroup()
                                                .addComponent(si12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(no12))))
                                    .addComponent(Preg13, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Factores3)
                            .addGroup(vpPanel1Layout.createSequentialGroup()
                                .addComponent(RazSoc)
                                .addGap(18, 18, 18)
                                .addComponent(RazSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Factores1)
                            .addComponent(Factores2)
                            .addGroup(vpPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Preg16, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Preg15, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(vpPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(si16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(no16))))
                            .addGroup(vpPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(Preg18))))
                    .addGroup(vpPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(Preg20, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(vpPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(Preg14, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, vpPanel1Layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(Preg19, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(vpPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(si13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(no13)))
                .addContainerGap())
        );
        vpPanel1Layout.setVerticalGroup(
            vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vpPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RazSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RazSoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Factores1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Preg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(si1)
                    .addComponent(no1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Preg2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no2)
                    .addComponent(si2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Preg3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(no3)
                    .addComponent(si3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Preg4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(si4)
                    .addComponent(no4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Preg5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(si5)
                    .addComponent(no5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vpPanel1Layout.createSequentialGroup()
                        .addComponent(Preg6)
                        .addGap(20, 20, 20))
                    .addComponent(Preg17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(si6)
                    .addComponent(no6))
                .addGap(10, 10, 10)
                .addComponent(Factores2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Factores4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Preg7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(si7)
                    .addComponent(no7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Preg8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(si8)
                    .addComponent(no8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Preg9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(si9)
                    .addComponent(no9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Preg10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(si10)
                    .addComponent(no10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Preg11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(si11)
                    .addComponent(no11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Preg12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(si12)
                    .addComponent(no12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Preg13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Preg19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(si13)
                    .addComponent(no13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Factores3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Preg14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Preg18)
                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vpPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(Preg15))
                    .addGroup(vpPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(si14)
                            .addComponent(no14))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Preg20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(si15)
                    .addComponent(no15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Preg16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(si16)
                    .addComponent(no16))
                .addGap(11, 11, 11))
        );

        vpPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Panel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        Panel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        Panel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        Panel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Panel4Layout = new javax.swing.GroupLayout(Panel4);
        Panel4.setLayout(Panel4Layout);
        Panel4Layout.setHorizontalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Panel4Layout.setVerticalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout vpPanel2Layout = new javax.swing.GroupLayout(vpPanel2);
        vpPanel2.setLayout(vpPanel2Layout);
        vpPanel2Layout.setHorizontalGroup(
            vpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vpPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        vpPanel2Layout.setVerticalGroup(
            vpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vpPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelmainLayout = new javax.swing.GroupLayout(panelmain);
        panelmain.setLayout(panelmainLayout);
        panelmainLayout.setHorizontalGroup(
            panelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelmainLayout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelmainLayout.createSequentialGroup()
                            .addComponent(vpPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(panelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(diag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vpPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panelmainLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelmainLayout.setVerticalGroup(
            panelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(22, 22, 22)
                .addGroup(panelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(panelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vpPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vpPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(diag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(panelmain);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1145, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void si1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_si1ActionPerformed
    }//GEN-LAST:event_si1ActionPerformed

    private void no1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no1ActionPerformed
    }//GEN-LAST:event_no1ActionPerformed

    private void no2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no2ActionPerformed
    }//GEN-LAST:event_no2ActionPerformed

    private void si2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_si2ActionPerformed
    }//GEN-LAST:event_si2ActionPerformed

    private void si3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_si3ActionPerformed
    }//GEN-LAST:event_si3ActionPerformed

    private void no3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no3ActionPerformed
    }//GEN-LAST:event_no3ActionPerformed

    private void si4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_si4ActionPerformed
    }//GEN-LAST:event_si4ActionPerformed

    private void no4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no4ActionPerformed
    }//GEN-LAST:event_no4ActionPerformed

    private void si5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_si5ActionPerformed
    }//GEN-LAST:event_si5ActionPerformed

    private void no5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no5ActionPerformed
    }//GEN-LAST:event_no5ActionPerformed

    private void si6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_si6ActionPerformed
    }//GEN-LAST:event_si6ActionPerformed

    private void no6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no6ActionPerformed
    }//GEN-LAST:event_no6ActionPerformed

    private void si7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_si7ActionPerformed
    }//GEN-LAST:event_si7ActionPerformed

    private void no7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no7ActionPerformed
    }//GEN-LAST:event_no7ActionPerformed

    private void si8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_si8ActionPerformed
    }//GEN-LAST:event_si8ActionPerformed

    private void no8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no8ActionPerformed
    }//GEN-LAST:event_no8ActionPerformed

    private void si9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_si9ActionPerformed
    }//GEN-LAST:event_si9ActionPerformed

    private void no9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no9ActionPerformed
    }//GEN-LAST:event_no9ActionPerformed

    private void si10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_si10ActionPerformed
    }//GEN-LAST:event_si10ActionPerformed

    private void no10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no10ActionPerformed
    }//GEN-LAST:event_no10ActionPerformed

    private void si11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_si11ActionPerformed
    }//GEN-LAST:event_si11ActionPerformed

    private void no11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no11ActionPerformed
    }//GEN-LAST:event_no11ActionPerformed

    private void si12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_si12ActionPerformed
    }//GEN-LAST:event_si12ActionPerformed

    private void no12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no12ActionPerformed
    }//GEN-LAST:event_no12ActionPerformed

    private void si13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_si13ActionPerformed
    }//GEN-LAST:event_si13ActionPerformed

    private void no13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no13ActionPerformed
    }//GEN-LAST:event_no13ActionPerformed

    private void si14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_si14ActionPerformed
    }//GEN-LAST:event_si14ActionPerformed

    private void no14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no14ActionPerformed
    }//GEN-LAST:event_no14ActionPerformed

    private void si15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_si15ActionPerformed
    }//GEN-LAST:event_si15ActionPerformed

    private void no15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no15ActionPerformed
    }//GEN-LAST:event_no15ActionPerformed

    private void si16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_si16ActionPerformed
    }//GEN-LAST:event_si16ActionPerformed

    private void no16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no16ActionPerformed
    }//GEN-LAST:event_no16ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(vp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(vp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(vp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(vp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new vp().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Diagnostico;
    private javax.swing.JLabel Factores1;
    private javax.swing.JLabel Factores2;
    private javax.swing.JLabel Factores3;
    private javax.swing.JLabel Factores4;
    public javax.swing.JPanel Panel1;
    public javax.swing.JPanel Panel2;
    public javax.swing.JPanel Panel3;
    public javax.swing.JPanel Panel4;
    private javax.swing.JLabel Preg1;
    private javax.swing.JLabel Preg10;
    private javax.swing.JLabel Preg11;
    private javax.swing.JLabel Preg12;
    private javax.swing.JLabel Preg13;
    private javax.swing.JLabel Preg14;
    private javax.swing.JLabel Preg15;
    private javax.swing.JLabel Preg16;
    private javax.swing.JLabel Preg17;
    private javax.swing.JLabel Preg18;
    private javax.swing.JLabel Preg19;
    private javax.swing.JLabel Preg2;
    private javax.swing.JLabel Preg20;
    private javax.swing.JLabel Preg3;
    private javax.swing.JLabel Preg4;
    private javax.swing.JLabel Preg5;
    private javax.swing.JLabel Preg6;
    private javax.swing.JLabel Preg7;
    private javax.swing.JLabel Preg8;
    private javax.swing.JLabel Preg9;
    private javax.swing.JLabel RazSoc;
    private javax.swing.JTextField RazSocial;
    public javax.swing.JPanel diag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JRadioButton no1;
    public javax.swing.JRadioButton no10;
    public javax.swing.JRadioButton no11;
    public javax.swing.JRadioButton no12;
    public javax.swing.JRadioButton no13;
    public javax.swing.JRadioButton no14;
    public javax.swing.JRadioButton no15;
    public javax.swing.JRadioButton no16;
    public javax.swing.JRadioButton no2;
    public javax.swing.JRadioButton no3;
    public javax.swing.JRadioButton no4;
    public javax.swing.JRadioButton no5;
    public javax.swing.JRadioButton no6;
    public javax.swing.JRadioButton no7;
    public javax.swing.JRadioButton no8;
    public javax.swing.JRadioButton no9;
    public javax.swing.JPanel panelmain;
    public javax.swing.JRadioButton si1;
    public javax.swing.JRadioButton si10;
    public javax.swing.JRadioButton si11;
    public javax.swing.JRadioButton si12;
    public javax.swing.JRadioButton si13;
    public javax.swing.JRadioButton si14;
    public javax.swing.JRadioButton si15;
    public javax.swing.JRadioButton si16;
    public javax.swing.JRadioButton si2;
    public javax.swing.JRadioButton si3;
    public javax.swing.JRadioButton si4;
    public javax.swing.JRadioButton si5;
    public javax.swing.JRadioButton si6;
    public javax.swing.JRadioButton si7;
    public javax.swing.JRadioButton si8;
    public javax.swing.JRadioButton si9;
    private javax.swing.JPanel vpPanel1;
    private javax.swing.JPanel vpPanel2;
    // End of variables declaration//GEN-END:variables
}
